version: 1.0.{build}
branches:
  only:
  - /develop/
max_jobs: 2
clone_depth: 10
clone_folder: c:\projects\vcmi\source
init:
- cmd: set QTDIR=C:\Qt\5.7\msvc2015
environment:
  BUILD_PLATFORM: x86
  BUILD_CONFIGURATION: Release
install:
- cmd: >-
    cd c:\projects\vcmi\

    curl -fsS -o vcmi_depends_%BUILD_PLATFORM%.zip https://dependencies.vcmi.download/msvc/vcmi_depends_%BUILD_PLATFORM%.zip

    7z x vcmi_depends_%BUILD_PLATFORM%.zip -odepends

    cd source

    git submodule update --init --recursive

    cd ..

    mkdir build_%BUILD_PLATFORM%

    cd build_%BUILD_PLATFORM%

    cmake -DCMAKE_TOOLCHAIN_FILE=../source/CI/msvc/appveyor_toolchain.txt ../source
build_script:
- cmd: >-
    cd c:\projects\vcmi\build_%BUILD_PLATFORM%

    msbuild vcmi.sln /p:configuration=%BUILD_CONFIGURATION% /maxcpucount:2

    IF "%APPVEYOR_REPO_TAG%"=="true" cpack


    mkdir dist_%BUILD_PLATFORM%

    copy %BUILD_CONFIGURATION%\*.exe dist_%BUILD_PLATFORM%

    copy %BUILD_CONFIGURATION%\*.dll dist_%BUILD_PLATFORM%

    copy %BUILD_CONFIGURATION%\lib\*.dll dist_%BUILD_PLATFORM%

    mkdir dist_%BUILD_PLATFORM%\AI

    copy %BUILD_CONFIGURATION%\AI\*.dll dist_%BUILD_PLATFORM%\AI

    cd dist_%BUILD_PLATFORM%

    mkdir platforms

    copy %QTDIR%\bin\Qt5Core.dll .

    copy %QTDIR%\bin\Qt5Gui.dll .

    copy %QTDIR%\bin\Qt5Widgets.dll .

    copy %QTDIR%\bin\Qt5Network.dll .

    copy %QTDIR%\plugins\platforms\qwindows.dll platforms

    7z a c:\projects\vcmi\source\vcmi-%BUILD_PLATFORM%-%BUILD_CONFIGURATION%.zip * -mx=7 -r -x!*.exp -x!*.lib

    7z a c:\projects\vcmi\source\vcmi-%BUILD_PLATFORM%-%BUILD_CONFIGURATION%.zip c:\projects\vcmi\depends\bin\*.dll -mx=7
artifacts:
- path: vcmi-x86-Release.zip
notifications:
  - provider: Slack
    incoming_webhook:
      secure: zxT3HTnxL744HiSv7ig7sjGL4LmJ8n3MsY8PEA/kinbVMkmcxrSgVBVkHV79RfSWSyq4oLMSRvMMpG8SuDWnf6oK/qvgaiAWfwwlCIiA7uQ=
